# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: qwen3-0-6b-agg
spec:
  backendFramework: vllm
  pvcs:
    - name: model-cache
      create: false
  services:
    Epp:
      componentType: epp
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/dynamo-frontend:1.2.0
          env:
            - name: DYN_KV_CACHE_BLOCK_SIZE
              value: "16"
            - name: DYN_MODEL_NAME
              value: "Qwen/Qwen3-0.6B"
            - name: DYN_DECODE_FALLBACK
              value: "true"
      eppConfig:
        config:
          plugins:
            - type: disagg-profile-handler
            - name: decode-filter
              type: label-filter
              parameters:
                label: "nvidia.com/dynamo-sub-component-type"
                validValues:
                  - "decode"
                allowsNoLabel: true
            - name: picker
              type: max-score-picker
            - name: dyn-decode
              type: dyn-decode-scorer
          schedulingProfiles:
            - name: decode
              plugins:
                - pluginRef: decode-filter
                  weight: 1
                - pluginRef: dyn-decode
                  weight: 1
                - pluginRef: picker
                  weight: 1
    decode:
      componentType: worker
      envFromSecret: hf-token-secret
      volumeMounts:
        - name: model-cache
          mountPoint: /opt/models
      sharedMemory:
        size: 2Gi
      frontendSidecar:
        image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.0
        args:
          - -m
          - dynamo.frontend
          - --router-mode
          - direct
      extraPodSpec:
        mainContainer:
          env:
            - name: SERVED_MODEL_NAME
              value: "Qwen/Qwen3-0.6B"
            - name: MODEL_PATH
              value: "Qwen/Qwen3-0.6B"
            - name: HF_HOME
              value: /opt/models
            - name: DYN_STORE_KV
              value: "mem"
          args:
          - "python3 -m dynamo.vllm --model $MODEL_PATH --served-model-name $SERVED_MODEL_NAME --tensor-parallel-size 1 --data-parallel-size 1 --gpu-memory-utilization 0.90 --enable-prefix-caching --kv-events-config '{\"enable_kv_cache_events\":true}' --block-size 16"
          command:
          - /bin/sh
          - -c
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.0
          workingDir: /workspace/examples/backends/vllm
      replicas: 2
      resources:
        limits:
          gpu: "1"
        requests:
          gpu: "1"
