# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1beta1
kind: DynamoGraphDeployment
metadata:
  name: llama3-70b-disagg
spec:
  backendFramework: vllm
  components:
  - name: Epp
    type: epp
    replicas: 1
    eppConfig:
      config:
        plugins:
        - type: disagg-profile-handler
        - name: prefill-filter
          type: label-filter
          parameters:
            label: nvidia.com/dynamo-component-type
            validValues:
            - prefill
            allowsNoLabel: false
        - name: decode-filter
          type: label-filter
          parameters:
            label: nvidia.com/dynamo-component-type
            validValues:
            - decode
            allowsNoLabel: false
        - name: picker
          type: max-score-picker
        - name: dyn-prefill
          type: dyn-prefill-scorer
        - name: dyn-decode
          type: dyn-decode-scorer
        schedulingProfiles:
        - name: prefill
          plugins:
          - pluginRef: prefill-filter
            weight: 1
          - pluginRef: dyn-prefill
            weight: 1
          - pluginRef: picker
            weight: 1
        - name: decode
          plugins:
          - pluginRef: decode-filter
            weight: 1
          - pluginRef: dyn-decode
            weight: 1
          - pluginRef: picker
            weight: 1
    podTemplate:
      spec:
        containers:
        - name: main
          env:
          - name: DYN_KV_CACHE_BLOCK_SIZE
            value: "128"
          - name: DYN_MODEL_NAME
            value: RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
          - name: DYN_ENFORCE_DISAGG
            value: "true"
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/dynamo-frontend:1.2.0
  - name: prefill
    type: prefill
    replicas: 2
    sharedMemorySize: 80Gi
    frontendSidecar: sidecar-frontend
    podTemplate:
      spec:
        affinity:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: nvidia.com/dynamo-component-class
                    operator: In
                    values:
                    - worker
                topologyKey: kubernetes.io/hostname
        containers:
        - name: main
          args:
          - python3 -m dynamo.vllm --model $MODEL_PATH --served-model-name $SERVED_MODEL_NAME
            --tensor-parallel-size 2 --data-parallel-size 1 --disaggregation-mode
            prefill --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
            --gpu-memory-utilization 0.90 --enable-prefix-caching --block-size 128
            --kv-events-config '{"enable_kv_cache_events":true}'
          command:
          - /bin/sh
          - -c
          env:
          - name: SERVED_MODEL_NAME
            value: RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
          - name: MODEL_PATH
            value: RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
          - name: HF_HOME
            value: /opt/models
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.0
          resources:
            limits:
              nvidia.com/gpu: "2"
            requests:
              nvidia.com/gpu: "2"
          volumeMounts:
          - mountPath: /opt/models
            name: model-cache
          workingDir: /workspace/examples/backends/vllm
        - name: sidecar-frontend
          args:
          - -m
          - dynamo.frontend
          - --router-mode
          - direct
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/dynamo-frontend:1.2.0
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache
  - name: decode
    type: decode
    replicas: 1
    sharedMemorySize: 80Gi
    frontendSidecar: sidecar-frontend
    podTemplate:
      spec:
        affinity:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: nvidia.com/dynamo-component-class
                    operator: In
                    values:
                    - worker
                topologyKey: kubernetes.io/hostname
        containers:
        - name: main
          args:
          - python3 -m dynamo.vllm --model $MODEL_PATH --served-model-name $SERVED_MODEL_NAME
            --tensor-parallel-size 4 --data-parallel-size 1 --disaggregation-mode
            decode --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
            --gpu-memory-utilization 0.90 --block-size 128
          command:
          - /bin/sh
          - -c
          env:
          - name: SERVED_MODEL_NAME
            value: RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
          - name: MODEL_PATH
            value: RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
          - name: HF_HOME
            value: /opt/models
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.0
          resources:
            limits:
              nvidia.com/gpu: "4"
            requests:
              nvidia.com/gpu: "4"
          volumeMounts:
          - mountPath: /opt/models
            name: model-cache
          workingDir: /workspace/examples/backends/vllm
        - name: sidecar-frontend
          args:
          - -m
          - dynamo.frontend
          - --router-mode
          - direct
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/dynamo-frontend:1.2.0
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache